AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  itineraries--serverless-googlesheets

  SAM Template for itineraries--serverless-googlesheets
Globals:
  Function:
    Timeout: 3
    Layers:
      - !Ref GoogleApiPythonClientLayer
    Environment:
      Variables:
        SERVICE_ACCOUNT: null
Parameters:
  StageName:
    Type: String
    Default: Prod

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
  GoogleApiPythonClientLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/google-api-python-client/layer-content.zip
      LicenseInfo: Apache-2.0
      CompatibleRuntimes:
        - python3.13
  GetAllItinerariesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_all_itineraries.lambda_handler
      Runtime: python3.13
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: HttpApi
            Path: /itineraries
            Method: GET

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
