AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  itineraries--serverless-googlesheets

  SAM Template for itineraries--serverless-googlesheets
Globals:
  Function:
    Timeout: 3
Parameters:
  StageName:
    Type: String
    Default: Prod

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
  GoogleApiPythonClientLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/google-api-python-client/layer-content.zip
      LicenseInfo: Apache-2.0
      CompatibleRuntimes:
        - python3.13

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
