AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  itineraries--serverless-googlesheets

  SAM Template for itineraries--serverless-googlesheets
Globals:
  Function:
    Timeout: 3
Parameters:
  StageName:
    Type: String
    Default: Prod

