AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  itineraries--serverless-googlesheets

  SAM Template for itineraries--serverless-googlesheets
Globals:
  Function:
    Timeout: 10
    Layers:
      - !Ref GoogleApiPythonClientLayer
    Environment:
      Variables:
        # SERVICE_ACCOUNT_INFO: null
        SERVICE_ACCOUNT_PARAMETER_NAME: !Ref ServiceAccountInfoParameter
Parameters:
  StageName:
    Type: String
    Default: Prod

Resources:
  ServiceAccountInfoParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: manually replace with SecureString after creation
      Value: placeholder
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
  GoogleApiPythonClientLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/google-api-python-client/layer-content.zip
      LicenseInfo: Apache-2.0
      CompatibleRuntimes:
        - python3.13
  GetAllItinerariesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_all_itineraries.lambda_handler
      Runtime: python3.13
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /itineraries
            Method: GET
  CreateItineraryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create_itinerary.lambda_handler
      Runtime: python3.13
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /itineraries
            Method: POST
  GetArchivedItinerariesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_archived_itineraries.lambda_handler
      Runtime: python3.13
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /archives
            Method: GET
  DeleteArchivedItineraryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete_archived_itinerary.lambda_handler
      Runtime: python3.13
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /archives/{id}
            Method: DELETE
  GetItineraryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_itinerary.lambda_handler
      Runtime: python3.13
      MemorySize: 256
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /itineraries/{id}
            Method: GET
  ArchiveItineraryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: archive_itinerary.lambda_handler
      Runtime: python3.13
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /itineraries/{id}
            Method: DELETE
  CreateActivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create_activity.lambda_handler
      Runtime: python3.13
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /itineraries/{id}
            Method: POST
  DeleteActivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete_activity.lambda_handler
      Runtime: python3.13
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ServiceAccountInfoParameter
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /itineraries/{id}/{activity_type}/{index}
            Method: DELETE

Outputs:
  ServiceAccountInfoParameter:
    Description: Parameter name
    Value: !Ref ServiceAccountInfoParameter
  HttpApiUrl:
    Description: URL of your API endpoint
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/
  HttpApiId:
    Description: Api id of HttpApi
    Value: !Ref HttpApi
  GetAllItinerariesFunction:
    Description: GetAllItinerariesFunction ARN
    Value: !GetAtt GetAllItinerariesFunction.Arn
  GetItineraryFunction:
    Description: GetItineraryFunction ARN
    Value: !GetAtt GetItineraryFunction.Arn
  GetArchivedItinerariesFunction:
    Description: GetArchivedItinerariesFunction ARN
    Value: !GetAtt GetItineraryFunction.Arn
  DeleteArchivedItineraryFunction:
    Description: DeleteArchivedItineraryFunction ARN
    Value: !GetAtt DeleteArchivedItineraryFunction.Arn
  CreateItineraryFunction:
    Description: CreateItineraryFunction ARN
    Value: !GetAtt CreateItineraryFunction.Arn
  ArchiveItineraryFunction:
    Description: ArchiveItineraryFunction ARN
    Value: !GetAtt ArchiveItineraryFunction.Arn
  CreateActivityFunction:
    Description: CreateActivityFunction ARN
    Value: !GetAtt CreateActivityFunction.Arn
  DeleteActivityFunction:
    Description: DeleteActivityFunction ARN
    Value: !GetAtt DeleteActivityFunction.Arn
